apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: graph-docs
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: staging.thegraph.com
      http:
        paths:
          - path: /(en|es|ar/ko/zh/ja/vi)/docs
            backend:
              serviceName: graph-docs
              servicePort: http
